/*
 * Copyright (c) 1997, 2022 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b24-ea3
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2006.01.20 at 03:59:03 PM IST
//


package com.sun.xml.security.core.dsig;

import com.sun.xml.ws.security.opt.crypto.dsig.SignatureValue;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.sun.xml.ws.security.opt.crypto.dsig.SignedInfo;
import com.sun.xml.ws.security.opt.crypto.dsig.keyinfo.KeyInfo;


/**
 * <p>Java class for SignatureType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="SignatureType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{http://www.w3.org/2000/09/xmldsig#}SignedInfo"/>
 *         <element ref="{http://www.w3.org/2000/09/xmldsig#}SignatureValue"/>
 *         <element ref="{http://www.w3.org/2000/09/xmldsig#}KeyInfo" minOccurs="0"/>
 *         <element ref="{http://www.w3.org/2000/09/xmldsig#}Object" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlRootElement(name="SignatureType")
@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "SignatureType")
@XmlType(name = "SignatureType", propOrder = {
    "signedInfo",
    "signatureValue",
    "keyInfo",
    "object"
})
public class SignatureType {

    @XmlElement(name = "SignedInfo", namespace = "http://www.w3.org/2000/09/xmldsig#" ,type=com.sun.xml.ws.security.opt.crypto.dsig.SignedInfo.class)
    protected SignedInfo signedInfo;
    @XmlElement(name = "SignatureValue", namespace = "http://www.w3.org/2000/09/xmldsig#" , type=com.sun.xml.ws.security.opt.crypto.dsig.SignatureValue.class)
    protected SignatureValue signatureValue;
    @XmlElement(name = "KeyInfo", namespace = "http://www.w3.org/2000/09/xmldsig#" , type=com.sun.xml.ws.security.opt.crypto.dsig.keyinfo.KeyInfo.class)
    protected KeyInfo keyInfo;
    @XmlElement(name = "Object", namespace = "http://www.w3.org/2000/09/xmldsig#")
    protected List<ObjectType> object;
    @XmlAttribute(name = "Id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;

    /*
      Gets the value of the signedInfo property.

      @return
     *     possible object is
     *     {@link SignedInfoType }

     */
    /*public SignedInfoType getSignedInfo() {
        return signedInfo;
    }*/

    /**
     * Sets the value of the signedInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link SignedInfoType }
     *
     */
    public void setSignedInfo(SignedInfo value) {
        this.signedInfo = value;
    }

    /*
      Gets the value of the signatureValue property.

      @return
     *     possible object is
     *     {@link SignatureValueType }

     */
    /*c
        return signatureValue;
    }*/

    /**
     * Sets the value of the signatureValue property.
     *
     * @param value
     *     allowed object is
     *     {@link SignatureValueType }
     *
     */
    public void setSignatureValue(SignatureValue value) {
        this.signatureValue = value;
    }

    /*
      Gets the value of the keyInfo property.

      @return
     *     possible object is
     *     {@link KeyInfoType }

     */
    /*public KeyInfoType getKeyInfo() {
        return keyInfo;
    }*/

    /**
     * Sets the value of the keyInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link KeyInfoType }
     *
     */
    public void setKeyInfo(KeyInfo value) {
        this.keyInfo = value;
    }

    /**
     * Gets the value of the object property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the object property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>{@code
     *    getObject().add(newItem);
     * }</pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectType }
     *
     *
     */
    public List<ObjectType> getObject() {
        if (object == null) {
            object = new ArrayList<>();
        }
        return this.object;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

}
