/*
 * Copyright (c) 1997, 2022 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

package com.sun.xml.ws.transport.tcp.servicechannel.stubs;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1.1-hudson-2014-Nightly
 * Generated source version: 2.1
 *
 */
@WebServiceClient(name = "ServiceChannelWSImplService", targetNamespace = "http://servicechannel.tcp.transport.ws.xml.sun.com/")
public class ServiceChannelWSImplService
    extends Service
{

    private final static URL SERVICECHANNELWSIMPLSERVICE_WSDL_LOCATION;

    static {
        SERVICECHANNELWSIMPLSERVICE_WSDL_LOCATION = com.sun.xml.ws.transport.tcp.servicechannel.ServiceChannelWSImpl.class.getResource("ServiceChannelWSImplService.wsdl");
    }

    public ServiceChannelWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceChannelWSImplService() {
        super(SERVICECHANNELWSIMPLSERVICE_WSDL_LOCATION, new QName("http://servicechannel.tcp.transport.ws.xml.sun.com/", "ServiceChannelWSImplService"));
    }

    /**
     *
     * @return
     *     returns ServiceChannelWSImpl
     */
    @WebEndpoint(name = "ServiceChannelWSImplPort")
    public ServiceChannelWSImpl getServiceChannelWSImplPort() {
        return super.getPort(new QName("http://servicechannel.tcp.transport.ws.xml.sun.com/", "ServiceChannelWSImplPort"), ServiceChannelWSImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceChannelWSImpl
     */
    @WebEndpoint(name = "ServiceChannelWSImplPort")
    public ServiceChannelWSImpl getServiceChannelWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicechannel.tcp.transport.ws.xml.sun.com/", "ServiceChannelWSImplPort"), ServiceChannelWSImpl.class, features);
    }

}
