<?xml version="1.0"?>
<!--

    Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Distribution License v. 1.0, which is available at
    http://www.eclipse.org/org/documents/edl-v10.php.

    SPDX-License-Identifier: BSD-3-Clause

-->

<definitions name="AddNumbers"

targetNamespace="http://example.org/AddNumbers/porttype"
          xmlns:tns="http://example.org/AddNumbers/porttype"
          xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
          xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
          xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
          xmlns="http://schemas.xmlsoap.org/wsdl/">

    <wsp:Policy wsu:Id="AddNumbersServicePolicy">
        <ExactlyOne>
            <All>
                <wsrm:RMAssertion xmlns:wsrm="http://schemas.xmlsoap.org/ws/2005/02/rm/policy"/>
            </All>
        </ExactlyOne>
    </wsp:Policy>
              
    <message name="Add">
    </message>

    <message name="AddResponse">
    </message>

    <portType name="AddNumbersPortType">
        <operation name="Add">
           <input message="tns:Add"/>
           <output message="tns:AddResponse"/>
        </operation>
    </portType>
</definitions>
