<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Distribution License v. 1.0, which is available at
    http://www.eclipse.org/org/documents/edl-v10.php.

    SPDX-License-Identifier: BSD-3-Clause

-->

<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:myns="http://example.org" name="DictService" targetNamespace="http://example.org">

  <wsp:Policy wsu:Id="Policy1">
    <myns:Assertion2/>
  </wsp:Policy>

  <wsdl:message name="DictRequest"/>
  <wsdl:message name="DictResponse"/>
  <wsdl:message name="DictFault"/>

  <wsdl:portType name="DictPortType">
    <wsp:PolicyReference URI="#Policy1"/>
    <wsdl:operation name="TranslateOperation">
      <wsdl:input name="Input" message="myns:DictRequest"/>
      <wsdl:output name="Output" message="myns:DictResponse"/>
      <wsdl:fault name="Fault" message="myns:DictFault"/>
    </wsdl:operation>
  </wsdl:portType>

</wsdl:definitions>
