/*
 * Copyright (c) 1997, 2022 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-3355
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2006.06.26 at 11:03:26 AM EDT
//


package com.sun.xml.ws.mex.client.schema;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.sun.xml.ws.mex.client.schema package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Location_QNAME = new QName("http://schemas.xmlsoap.org/ws/2004/09/mex", "Location");
    private final static QName _Dialect_QNAME = new QName("http://schemas.xmlsoap.org/ws/2004/09/mex", "Dialect");
    private final static QName _Identifier_QNAME = new QName("http://schemas.xmlsoap.org/ws/2004/09/mex", "Identifier");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sun.xml.ws.mex.client.schema
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Metadata }
     *
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link GetMetadata }
     *
     */
    public GetMetadata createGetMetadata() {
        return new GetMetadata();
    }

    /**
     * Create an instance of {@link MetadataReference }
     *
     */
    public MetadataReference createMetadataReference() {
        return new MetadataReference();
    }

    /**
     * Create an instance of {@link MetadataSection }
     *
     */
    public MetadataSection createMetadataSection() {
        return new MetadataSection();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/ws/2004/09/mex", name = "Location")
    public JAXBElement<String> createLocation(String value) {
        return new JAXBElement<>(_Location_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/ws/2004/09/mex", name = "Dialect")
    public JAXBElement<String> createDialect(String value) {
        return new JAXBElement<>(_Dialect_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/ws/2004/09/mex", name = "Identifier")
    public JAXBElement<String> createIdentifier(String value) {
        return new JAXBElement<>(_Identifier_QNAME, String.class, null, value);
    }

}
