//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MtomClient.localhost
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mtom/", ConfigurationName="MtomClient.localhost.MtomService")]
    public interface MtomService
    {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://mtom/)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MtomClient.localhost.echoBinaryResponse echoBinary(MtomClient.localhost.echoBinaryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoBinary", WrapperNamespace="http://mtom/", IsWrapped=true)]
    public partial class echoBinaryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] data;
        
        public echoBinaryRequest()
        {
        }
        
        public echoBinaryRequest(byte[] data)
        {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoBinaryResponse", WrapperNamespace="http://mtom/", IsWrapped=true)]
    public partial class echoBinaryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] @return;
        
        public echoBinaryResponse()
        {
        }
        
        public echoBinaryResponse(byte[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface MtomServiceChannel : MtomClient.localhost.MtomService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MtomServiceClient : System.ServiceModel.ClientBase<MtomClient.localhost.MtomService>, MtomClient.localhost.MtomService
    {
        
        public MtomServiceClient()
        {
        }
        
        public MtomServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MtomServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MtomServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MtomServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        MtomClient.localhost.echoBinaryResponse MtomClient.localhost.MtomService.echoBinary(MtomClient.localhost.echoBinaryRequest request)
        {
            return base.Channel.echoBinary(request);
        }
        
        public byte[] echoBinary(byte[] data)
        {
            MtomClient.localhost.echoBinaryRequest inValue = new MtomClient.localhost.echoBinaryRequest();
            inValue.data = data;
            MtomClient.localhost.echoBinaryResponse retVal = ((MtomClient.localhost.MtomService)(this)).echoBinary(inValue);
            return retVal.@return;
        }
    }
}
